# kubectl apply -k k8s/base
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-secret.yaml
  - backend-secret.yaml
  - postgres-init-configmap.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-service.yaml
  - frontend-deployment.yaml
